name: Build and Test

# Define o evento que dispara o workflow (exemplo: push para a branch principal)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Defina o sistema operacional que o GitHub Actions usará (Ubuntu, Windows, MacOS)
    
    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Configura o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Defina a versão do Node.js a ser usada

      # Passo 3: Instala as dependências
      - name: Install dependencies
        run: npm install

      # Passo 4: Execute os testes
      - name: build
        run: npm start
