name: Build and Run Express App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Install dependencies
        run: npm install

      - name: Start Express app and check if it runs
        run: |
          nohup npm start &  # Inicia a aplicação em segundo plano
          sleep 10  # Aguarda 10 segundos para o servidor iniciar
          curl --silent --fail http://localhost:3000  # Verifica se a aplicação está funcionando na porta 3000
        continue-on-error: true 
